### ISSUE TITLE
Firefox device type blank for Android smartphone/tablet

### ISSUE THREAD

**Issue by tomzmyslo** [podigee/device_detector#18]
When using DeviceDetector with Firefox on Android, the Mobile vs Tablet flag isn't registering to show the device type.

**Comment by peteygao** [comment]
Can you post the user agent that you're trying to detect? Otherwise we can't really debug it (I don't have an Android device to repro).

**Comment by tomzmyslo** [comment]
Here's the user agent from Firefox 47 on a Nexus 7 tablet:

`Mozilla/5.0 (Android 6.0.1; Tablet; rv:47.0) Gecko/47.0 Firefox/47.0`

**Comment by sliminas** [comment]
I encountered the same problem with `Mozilla/5.0 (Android 7.0; Mobile; rv:53.0) Gecko/53.0 Firefox/53.0`
The problem seems to be https://github.com/podigee/device_detector/blob/develop/lib/device_detector.rb#L170, where ` 'Android; Mobile;'` doesn't match `Android 7.0; Mobile;`. The same applies to tablets.

**Comment by yagooar** [comment]
Should be solved in https://github.com/podigee/device_detector/commit/5cdc27c325c12209c5d078900857e91bae7e2433
